config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('db2_project.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^post/', include('post.urls', namespace='post')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

db2_project/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<email>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

post/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from .views import PostListView, PostDetailView, PostCreateView, Post, \
    PostUpdateView, PostDeleteView, LikeCreateDeleteView

urlpatterns = [
    url(r'^$', PostListView.as_view(),  name='list_view'),
    url(r'^(?P<pk>\d+)/$', PostDetailView.as_view(), name='detail_view'),
    url(r'^(?P<pk>\d+)/like/$', csrf_exempt(LikeCreateDeleteView.as_view()), name='like'),
    url(r'^create/$', PostCreateView.as_view(), name='create_view'),
    url(r'^update/(?P<pk>\d+)/$', PostUpdateView.as_view(),
        name='update_view'),
    url(r'^delete/(?P<pk>\d+)/$', PostDeleteView.as_view(),
        name='delete_view'),
]

db2_project/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from .managers import CustomManager


@python_2_unicode_compatible
class User(AbstractUser):
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    email = models.EmailField(_('email address'), unique=True)
    birthday = models.DateField(null=True, blank=True)
    country = models.CharField(max_length=30, null=True, blank=True)
    city = models.CharField(max_length=30, null=True, blank=True)
    username = models.CharField(max_length=30, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomManager()

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'email': self.email})

post/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts')
    title = models.CharField(max_length=50)
    content = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    @property
    def likes_num(self):
        return len(self.likes.all())

    @property
    def shrinked_content(self):
        text = self.content
        if len(text) > 100:
            text = self.content[:100]
        return '{}...'.format(text)

    def __str__(self):
        return '{0} "{1}"'.format(self.author.email, self.title)


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name='comments')
    post = models.ForeignKey(Post, related_name='comments')
    text = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        text = self.text
        if len(text) > 20:
            text = self.text[:20]
        return '{0} "{1}..."'.format(self.author.email, text)

db2_project/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import extras


COUNTRYES = (
    ('Ukraine', 'Ukraine'),
    ('USA', 'USA'),
    ('United Kingdom', 'United Kingdom'),
    ('Australia', 'Australia'),
)

SITIES = (
    ('Kiev', 'Kiev'),
    ('Donetsk', 'Donetsk'),
    ('Dnepr', 'Dnepr'),
    ('Los Angeles', 'Los Angeles'),
    ('New York', 'New York'),
    ('San Francisco', 'San Francisco'),
    ('Sidney', 'Sidney'),
    ('Melbourne', 'Melbourne'),
)


class SignUpForm(UserCreationForm):
    birthday = forms.DateField(
        widget=extras.SelectDateWidget()
    )
    country = forms.ChoiceField(choices=COUNTRYES)
    city = forms.ChoiceField(choices=SITIES)

    class Meta:
        model = get_user_model()
        fields = ('email', 'password1', 'password2', 'birthday',
                  'city', 'country')

db2_project/users/views.py
from allauth.account.adapter import DefaultAccountAdapter
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'email'
    slug_url_kwarg = 'email'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'email': self.request.user.email})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', 'email', 'city', 'country', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'email': self.request.user.email})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(email=self.request.user.email)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = 'email'
    slug_url_kwarg = 'email'


class AccountAdapter(DefaultAccountAdapter):
    def get_login_redirect_url(self, request):
        return '/post'

post/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .models import Post, Comment


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'post/list.html'
    paginate_by = 4


# class PostDetailView(LoginRequiredMixin, DetailView):
#     model = Post
#     template_name = 'post/detail.html'


class PostDetailView(LoginRequiredMixin, View):

    @staticmethod
    def get_post(pk):
        return Post.objects.get(pk=pk)

    def get(self, request, pk):
        post = PostDetailView.get_post(pk)
        comments_list = post.comments.all()
        paginator = Paginator(comments_list, 3)

        page = request.GET.get('page')
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)
        return render(request, 'post/detail.html', {'post': post,
                                                    'comments': comments})

    def post(self, request, pk):
        post = PostDetailView.get_post(pk)
        text = request.POST.get('comment', False)
        if not text:
            message = 'You should to provide a comment text.'
            messages.error(self.request, message)
            return HttpResponseRedirect('/post/{}'.format(pk))
        Comment.objects.create(author=request.user, post=post, text=text)
        message = 'Comment successfully created'
        messages.success(self.request, message)
        return HttpResponseRedirect('/post/{}'.format(pk))


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    success_url = reverse_lazy('post:list_view')
    template_name = 'post/create.html'
    fields = ['title', 'content']

    def get_form(self, form_class=None):
        form = super(PostCreateView, self).get_form(form_class)
        for field in form.fields:
            form.fields[field].widget.attrs.update({'class': 'form-control'})
        return form

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        message = 'Post successfully created.'
        messages.success(self.request, message)
        return super(PostCreateView, self).form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    success_url = reverse_lazy('post:list_view')
    template_name = 'post/update.html'
    fields = ['title', 'content']

    def get_form(self, form_class=None):
        form = super(PostUpdateView, self).get_form(form_class)
        for field in form.fields:
            form.fields[field].widget.attrs.update(
                {'class': 'form-control'})
        return form

    def form_valid(self, form):
        message = 'Post successfully changed.'
        messages.success(self.request, message)
        return super(PostUpdateView, self).form_valid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('post:list_view')
    template_name = 'post/delete.html'

    def delete(self, request, *args, **kwargs):
        message = 'Post successfully deleted.'
        messages.success(self.request, message)
        return super(PostDeleteView, self).delete(self, request, *args,
                                                  **kwargs)


class LikeCreateDeleteView(LoginRequiredMixin, View):

    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        user = request.user
        if user in post.likes.all():
            post.likes.remove(user)
        else:
            post.likes.add(user)
        return JsonResponse({'likes': post.likes_num})

db2_project/templates/post/create.html
{%  extends "base.html" %}

{% load staticfiles %}

{% block content %}

    <h2 align="center">Create article</h2>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="button-right">
            <input type="submit" value="Save" class="btn btn-success">
        </div>
    </form>

{% endblock %}

db2_project/templates/post/delete.html
{%  extends "base.html" %}

{% load staticfiles %}

{% block content %}

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
    </form>

{% endblock content%}

db2_project/templates/post/detail.html
{%  extends "base.html" %}

{% load staticfiles %}

{% block content %}
    <div class="card">
      <h4 class="card-title" align="center">{{ post.title }}</h4>
      <p class="card-text">{{ post.content }}</p>
      <p class="card-text">
          <small>
              {{ post.author }}
              <span class="text-muted"> {{ post.published }}</span>
          </small>
          <span class="pull-right">
              <i
                class="fa fa-thumbs-up thumb-up"
                aria-hidden="true"
                data-id="{{ post.id }}"
              >
              </i> <span id="like">{{ post.likes_num }}</span>
          </span>
      </p>

    </div>

    {% if post.author == request.user %}
        <div class="buttons-row button-right">
            <a href="{% url 'post:update_view' post.pk %}" class="btn btn-success btn-md" >
                    Change post
            </a>
            <a href="{% url 'post:delete_view' post.pk %}" class="btn btn-success btn-md button-right" >
                    Delete post
            </a>
        </div>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <textarea name="comment" class="form-control comment-textarea" placeholder="Your comment can be here" required></textarea>
        <div class="button-right"> <input type="submit" value="Add comment" class="btn btn-success buttons-row"></div>
    </form>
    {% if comments %}
        <ul class="list-group">
            {% for comment in comments %}
                <li class="list-group-item comment-item">
                    <div><small><i>{{ comment.published }}</i> <b>{{ comment.author.email }}</b> has wrote:</small></div>
                    <div><small>{{ comment.text }}</small></div>
                </li>
            {% endfor %}
        </ul>
        <div class="pagination button-right">
            <span class="step-links">
                {% if comments.has_previous %}
                    <a href="?page={{ comments.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ comments.number }} of {{ comments.paginator.num_pages }}.
                </span>

                {% if comments.has_next %}
                    <a href="?page={{ comments.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% else %}
        <p>No comments</p>
    {% endif %}
{% endblock content %}

db2_project/templates/post/list.html
{%  extends "base.html" %}

{% load staticfiles %}

    {% block content %}
            <div class="card-deck">
                {% for post in object_list %}
                  <div class="card">
                    <div class="card-block">
                      <h4 class="card-title">
                          <a href="{% url 'post:detail_view' post.id %}">
                              {{ post.title }}
                          </a>
                      </h4>
                      <p class="card-text">{{ post.title }}</p>
                      <p class="card-text">{{ post.shrinked_content }}</p>
                      <p class="card-text">
                          <small class="text-muted">
                              {{ post.author }} {{ post.published }}
                          </small>
                      </p>
                    </div>
                  </div>
                {% endfor %}
            </div>

    {% if is_paginated %}
        <div class="pagination paginator-ctm button-right">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/post?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/post?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
        <div class="button-right"><a href="{% url 'post:create_view' %}" class="btn btn-success btn-md" >
            Add new post
        </a></div>
    </div>
{% endblock content %}

db2_project/templates/post/update.html
{%  extends "base.html" %}

{% load staticfiles %}

{% block content %}

    <h2 align="center">Change article</h2>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="button-right">
            <input type="submit" value="Change" class="btn btn-success">
        </div>
    </form>

{% endblock %}